### ISSUE TITLE
Possible plugin crash upon requesting PCA window.

### ISSUE THREAD

**Issue by leftdisconnected** [Rookiestyle/PasswordChangeAssistant#6]
## Overview
Experience issue upon clicking "Password Change Assistant..." in PCA drop-down icon on Edit Entry window.

## Steps to Reproduce
NOTE:  Experienced issue only once so far.
1.  Opened Edit Entry window for entry with intention of changing password.
2.  Clicked Password Change Assistanct dropdown icon on Edit Entry window.
3.  Clicked "Password Change Assistant..." control to open PCA child window.
4.  Pop-up error window containing text shown below.  Offered "Continue" or "Exit" (or similar) buttons.
5. Chose right-hand Exit (or similar) button and KeePass immediately disappeared from desktop and tray.
6. Re-opened KeePass and performed exact same procedure without errors.

## Context
[NOTE]: # (Provide any additional information you may have)
OS: Windows 7 64-bit
KeePass Version:  2.47
Plugin Version:  2.9

## Error Message

```
 See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at PasswordChangeAssistant.PasswordChangeAssistantExt.ShowPCAFormFromEntry(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4069.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.47.0.21109
    Win32 Version: 2.47.0.0
    CodeBase: file:///C:/users/<username>/portableapps/keepass/keepass.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
KeeAnywhere
    Assembly Version: 1.6.0.0
    Win32 Version: 1.6.0.0
    CodeBase: file:///C:/Users/<username>/AppData/Local/KeePass/PluginCache/<random_dir01>/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Assembly Version: 4.2.29.0
    Win32 Version: 4.2.29.0
    CodeBase: file:///C:/Users/<username>/AppData/Local/KeePass/PluginCache/<random_dir01>/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.3.21018
    CodeBase: file:///C:/Users/<username>/AppData/Local/KeePass/PluginCache/<random_dir01>/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Graph.Core
    Assembly Version: 1.9.0.0
    Win32 Version: 1.9.0.0
    CodeBase: file:///C:/Users/<username>/AppData/Local/KeePass/PluginCache/<random_dir01>/Microsoft.Graph.Core.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
PasswordChangeAssistant
    Assembly Version: 2.9.0.0
    Win32 Version: 2.9
    CodeBase: file:///C:/Users/<username>/AppData/Local/KeePass/PluginCache/xViCTaQ7Bt5rMoK4xfTJ/PasswordChangeAssistant.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.47.0.21109
    Win32 Version: 2.47.0.21109
    CodeBase: file:///C:/users/<username>/portableapps/keepass/KeePass.XmlSerializers.DLL
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Dropbox.Api
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.6718
    CodeBase: file:///C:/Users/<username>/AppData/Local/KeePass/PluginCache/<random_dir01>/Dropbox.Api.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------


```

**Comment by Rookiestyle** [comment]
Sorry to hear about this.

It's not possible to for me to further analyze as I understand it did occur only once and there is no way to reproduce it.

I'll leave this ticket open for a few days. In case you face this issue again, please go for "Continue" instead of "Exit" and let me know what happens.
Currently I have no clue to be honest

**Comment by leftdisconnected** [comment]
Understoood.  I was hoping that there might be a clue in the forms control exception list.  I've repeated the same actions a few times and no further errors have occurred.  I'll simply make another report if this happens again.  Thanks for your work on this extension and best of luck.
